### ISSUE TITLE
Population Changes

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#1014]
Remove garrison manpower population traits because they suck
Make boosting garrison manpower capacity population traits give empire manpower
Fix "On Happy" population traits not giving their proper boost bonus
Fix "On Anomaly" population trait boosts not giving the full amount they should
Fix Military population traits not giving their proper boost bonus
Bereaved - +60 Garrison Capacity on Strategic, +6 Manpower
Gnashast:
- Replace population bonuses with +100 Defensive Bombardment Damage, 0.2 Luxury Deposit Bonus
- Replace Collection 2 with: +100 Defensive Bombardment per Pop, +25% Luxury Deposit Value on System

Harmony:
- +2 Science on Strategic Deposits, +0.2 Strategic Deposit bonus
- Replace Collection 2 with: +5% Science, +25% Strategic Deposit Value on System

Illo - +2 Science, +1 Influence on Hot
Sowers - +1 food, +3 ind in fertile, remove anti-depletion
Tikanan - +60 Garrison Capacity, +6 Manpower on Fertile
Bhagaba - +2 Influence, +2 on Fertile
Sheredyn - Make Sheredyn use ESG traits instead of vanilla traits
Give UE & Riftborn Population Pragmatic (Militarist to Scientist, They should have this, but it is currently bugged)
Try Giving Vodyani Population the Fanatical trait (if it is disruptive, get rid of it, They should have this but are bugged)

Amblyr:
- Replace population bonuses with +2 Industry on Temperate, +2 Dust
- Replace Investors (Pacifist -> Industrialist) political trait with Anti-Militarist

**Comment by wakystuf** [comment]
This generally seems fine. A few things:
* Don't forget that the Gnashast and some of the other collection bonuses are also terrible.
* I'd generally suggest more MP gen instead of Garrison Capacity, since the latter can get weird with boosting (IE, it doubles, then drops in half again every 10 turns). Unless we can make the boost apply disproportionately to whatever the other part of the pop does
* I think we already did the Sowers, but I could be remembering wrong
