### ISSUE TITLE
Cool Collections Changes

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#1058]
Make Cool Collections population modifier effect be an added percentage instead of a multiplier
Buff second effect a bit (exclude for horatio)? :))

**Comment by NoProblemWithThisAcc** [comment]
How about a horatio-specific version that instead of +20% any applicable FIDSI collection and +15% any racial bonuses, only effects the splices' FIDSI +25%, rounded up.

**Comment by wakystuf** [comment]
Done. The addition thing is tricky since I worry about what will happen if there are none, but I buffed the numbers quite significantly on both portions of the law (and the corresponding UF hero skill).

@captaincobbs the GUI for this is a huge pain with all the foreign localization, but I think I got them all. Can you briefly check that you agree it's showing properly in the GUI?
