### ISSUE TITLE
Umbral Choir Questline Rework

### ISSUE THREAD

**Issue by Doruk-Coskun** [wakystuf/ESG-Mod#299]

**Comment by Doruk-Coskun** [comment]
Low Quality Foundations doesnt work.
![image](https://user-images.githubusercontent.com/25507419/106383062-a5c06c80-63d4-11eb-8372-38a2aecb4d3e.png)

**Comment by wakystuf** [comment]
I didn't think that Low Quality Foundations were related to the questline, but I think that issue (which I've noticed as well) might be fixed by the separate fix to "Planet FIDS and FIDSI cannot be negative." I haven't tested that fix yet, however.

**Comment by captaincobbs** [comment]
I don't think so either.

**Comment by wakystuf** [comment]
OK, sounds good. So should this be marked as Finished, or was there another change being made as well?

**Comment by captaincobbs** [comment]
I'm still trying to get Chaos to respond, I'm not at all involved with quest stuff, so I have no idea what's happening here.

**Comment by captaincobbs** [comment]
This was delayed

**Comment by wakystuf** [comment]
OK, sounds good. I'll remove the Needs Documentation label then, since I mostly use that to keep track of my to-do list

**Comment by wakystuf** [comment]
Is this still an open issue, or do the changes by @Arpharnator solve this? I realize he didn't change the quests directly, but I'm not sure what this is intended to fix exactly

**Comment by Arpharnator** [comment]
UC quest is still shit imo so it's likely to be changed

**Comment by wakystuf** [comment]
Well, could always partially reduce the nerf on Burning Metal. That plus the extra hacking op used to be pretty great as rewards, I think. Is there another issue with it?

**Comment by wakystuf** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link id=Main-File rel=Main-File
href="file:///C:\Users\William\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\William\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



VANILLA
--
  |   |   |   |   |   |   |   |   |   |   |   |  
  |   | Pacifist |   | Scientist |   |   |   |   |   |  
Chapter |   | Goal | Reward |   | Goal | Reward |   |   |   |   |   |  
1.1 |   | Cordial with a minor | 30 T1 lux |   | Discover 10 systems | 200 Dust |   |   |   |   |   |  
1.2 |   | Net influence of N+35 | Infl module |   | BW of N+15 | Sci module |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  |   | Pacifist |   | Scientist
  |   | Goal | Reward |   |   |   |   | Goal | Reward |   |   |  
2 |   | Have N+2 systems | Hero |   |   |   |   | Hack special node in middle | Hero +2 XP/turn, +100% healing |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  |   | Militarist |   | Pacifist |   | Scientist |   | Pacifist
  |   | Goal | Reward |   | Goal | Reward |   | Goal | Reward |   | Goal | Reward
3 |   | Create ship of X offense | Law: +5 ind per sleeper |   | Cloaked fleet to X system | Law: +3 infl per sleeper |   | Have X+2 Backdoors | Burning Metal |   | Embed a sleeper in X system | Law: -75% BW cost from backdoors
4 |   | Invade/destroy X system | +20% Evasion |   | Produce X+150 dust with trade | +5 BW per system |   | Hack a Capital | +1 hacking operation |   | Have sleepers on 3 systems | +5/10 approval per Peace/alliance, +1% science per sleeper
  |   |   |   |   |   |   |   |   |   |   |   |  
ESG
  |   |   |   |   |   |   |   |   |   |   |   |  
  |   | Pacifist |   | Scientist |   |   |   |   |   |  
Chapter |   | Goal | Reward |   | Goal | Reward |   |   |   |   |   |  
1.1 |   | Cordial with a minor | 50 T1 strat |   | Discover 10 systems | 500 Dust |   |   |   |   |   |  
1.2 |   | Net influence of N+35 | -33% peaceful diplo cost |   | BW of N+15 | +2 passive vision on ships |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  |   | Pacifist |   | Scientist
  |   | Goal | Reward |   |   |   |   | Goal | Reward |   |   |  
2 |   | Have N+2 systems | Hero (overseer) |   |   |   |   | Hack special node in middle | Void hack speed = starlane hack speed |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  |   | Militarist |   | Pacifist |   | Scientist |   | Pacifist
  |   | Goal | Reward |   | Goal | Reward |   | Goal | Reward |   | Goal | Reward
3 |   | Create ship of X offense | +4 MP per BW |   | Cloaked fleet to X system | +0.5 approval per sleeper |   | Have X+2 Backdoors | +4/4/2% node/warp/node speed per backdoor |   | Embed a sleeper in X system | Ecstatic sanctuaries (no impact on capital approval)
4 |   | Invade/destroy X system | +20% Evasion |   | Produce X+150 dust with trade | +2 FIDS per BW |   | Hack a Capital | +1 hacking operation |   | Have sleepers on 3 systems | +5 approval per Assimilated minor, +1% science per sleeper
  |   |   |   |   |   |   |   |   |   |   |   |  
  |   | All chapter 3 laws to   become empire improvements (otherwise none of them will get used with the law   rework laws) |   |   |   |   |   |  
  |   | Make sure Peacemaker   sleeper system is nearby-ish |   |   |   |   |   |   |   |  
  |   | Make sure special node is   nearby-ish in Sci chapter 2 |   |   |   |   |   |   |   |  



</body>

</html>

**Comment by wakystuf** [comment]
![image](https://user-images.githubusercontent.com/79942510/130693878-9810013d-645a-4880-a074-9b5e152122b8.png)
