### ISSUE TITLE
Settings Screen Changes

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#690]
- Fixed the naming of many settings to make it consistent with the standard ES2 title case
- Added more in-depth description to many settings
- Tied anomaly/curiosity count to galaxy size rather than independent settings
- Replaced anomaly/curiosity count settings with anomaly (curiosity slider disabled until I can fix it) additional settings
- Moved all ESG settings to ESG Settings tab

**Comment by wakystuf** [comment]
Update: Also fixed the minors setting. It turns out that there is only one parameter that matters for that, which is a multiplier applied to the default number of minors (default = [# players] + [# minors from the galaxy size]). I reworked the increments to account for that, and also updated the labels to explain how it's really working.
