### ISSUE TITLE
Military Behemoth Buffs

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#817]
(Proposed By Chaos)
Give Military Behemoths special versions of the coordinator-specific modules that are fleet-wide instead of flotilla-wide.

**Comment by Arpharnator** [comment]
Military behemoth have like 2-3 support slots
Maybe increase the raw power of one because they are weak

**Comment by Arpharnator** [comment]
give juggernauts the benefits of this tech, they don't atm
![image](https://user-images.githubusercontent.com/49691625/148266770-1506e88f-59c2-448b-a2ca-db09363b1110.png)

**Comment by wakystuf** [comment]
Agreed. I didn't even know that, since I never build them, but that makes sense

**Comment by NoProblemWithThisAcc** [comment]
We all agree that they are teh sux, but can we at least agree on what they are _supposed_ to do?

Since they are like a bijillion CP, are they supposed to be tanks? Are they supposed to have all teh support slots and be a non-tank but ignored support carrier? Are they supposed to have killer DPS with lots of weapon slots? What exactly was the original goal for them (prior to specialization) because they just fail at all of these roles.

**Comment by Arpharnator** [comment]
idk you'd need to ask cobbs,, but what i know right now is that they are extremely tanky ships (except to bombers) later into the game with fairly low damage because of the lack of weapon slots.

**Comment by NoProblemWithThisAcc** [comment]
Hey if we want to make them into actual tanks. I'm _all_ for that. Pre-carrier nerfs, I used to use 1 super tanky carrier per lane as my tanks. Now I can't and it makes me sad because (aside from crappy juggs) there are no actual tanks ... besides just being 'up' a tier on your enemy (ie using high CP designs while they are using attackers or using carriers when they only have hunters)

**Comment by wakystuf** [comment]
Protectors are your new tanks, though admittedly they don't do well vs BEB

**Comment by Zingybird** [comment]
They are going to when I recover from covid I will finish this whole thing, they are basically going  to become tanky coordinators that have modules that are going to be fleet wide so shielding health etc I have a write up if you are interested

**Comment by Arpharnator** [comment]
you mean with the three support slots they have

also if you have a writeup send it

**Comment by Zingybird** [comment]
[behemoths.docx](https://github.com/wakystuf/ESG-Mod/files/7831745/behemoths.docx)

**Comment by Zingybird** [comment]
I guess I forgot to put this in ages ago

**Comment by Arpharnator** [comment]
sus

**Comment by captaincobbs** [comment]
Merged into #1091
