### ISSUE TITLE
Hull health rebalance

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#935]
Per discussion with @Eighth-of-Third , proposal:
* Nerf base Carrier health to 20k (3k per CP, rounded nicely)
* Nerf base Hunter health to 6k (2k per CP)
* Nerf base Coordinator health to 9k (3k per CP)

Current amounts:
![image](https://user-images.githubusercontent.com/79942510/143811938-d2c375f5-31c9-46eb-bea9-d63c73682b79.png)

**Comment by Arpharnator** [comment]
I suppose this is meant to help attackers kill carriers, alongside some help early on for attacker to deal with hunters.
I think that if you do this then you need to deal with the bombers dmg, because now you'll need 33% less to kill a carrier.

Another way you could do this is adding empire improvements that increase attacker/protector health, making them able to deal with BEB to some degree (also you'd probably want shields to do something against BEB and not nothing for a proper fix). 
Something that could be interesting of that's no good is to make it so that defenses give more hp/Shield to an attacker/defender, thus making it so that they can't be versatile, to make up for their low value strat cost later on, unless retrofited.

**Comment by Arpharnator** [comment]
It makes it so that you can get a Dynamic of being able to field more versatile fleets as you get better ships researched, however having thé 1cps still useful but not as versatile for a comparable fleet, thus needing to spend more T1 resources as the versatility is done by using multiple fleets

**Comment by wakystuf** [comment]
Update: also buffing health from defense modules.

I don't think we need to mess with squadrons, since I've buffed flak efficiency vs squadrons so dramatically, even vs prior versions of ESG (I think another 100% or something, plus another multiplicative 100% from the hero skill, for +300% total)

**Comment by Arpharnator** [comment]
Didn't the hero skill get cancelled?
