### ISSUE TITLE
Add all minor factions (including dlc) to the curio pool

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#982]

**Comment by Provolonage** [comment]
Can we remove certain trash minors from the curio pool since we wont buff them to have a reason to exist (Illo, Gnashast, Tikanann)

**Comment by wakystuf** [comment]
@Provolonage 
Shouldn't we buff the minors instead? If somebody can create a chart with all of them (pop effect, collection II and III) then I can look into it.

**Comment by Provolonage** [comment]
sure ill work on making a chart today so expect it in 2022

**Comment by ThanosDeGraf** [comment]
If you want the three "trash" minors mentioned by provo, here they are. The second faction trait is always the rarer one. Of course, I consulted the changelog for each race and try to reflect those here.

Tikanan:

- Per Pop Effect: +5 Manpower per turn, +5 Manpower per turn on Fertile
- Trait I "Swarming Infantry ": 15% more Troop Deployment on Ground Battle
- Trait II "Infinite Soldiers": +100 Manpower per turn on Empire
- Col Bonus II: +50 Manpower per turn on systems with Tikanan
- Col Bonus III: Unlock "Swarm Tactics" ground battle card (Buffed Blitz with 20% less health and 40% more Troops deployed)

Illo:

- Per Pop Effect: +1 Influence on Hot
- Trait I Behemoth Awe: +40 Influence on Empire per Behemoth Owned by Empire
- Trait II Endless Maintenance: -25% Upkeep Cost on Juggernauts
- Col Bonus II: +10% Influence on systems with Illo.
- Col Bonus III: "Fist of Fear Edict" Law (+5% Influence per Empires at War on Systems)

Gnashast:

- Per Pop Effect: +100 Damage done to Attacker during ground battle. +100 Damage done to Attacker during ground battle on Fertile.
- Trait I Hard Hitters: +750 Damage done to attacker during ground battle on Systems
- Trait II Monstrous Opponents: +15% Troop Damage, +15% Troop Health on Empire
- Col Bonus II: +300 Damage to attacker during ground battle on systems with Gnashast.
- Col Bonus III: "Gnashast battle ground tactic" (Buffed Protect System with +40% defending Troop Health, 1000 Damage dealt to attackers minimum and 1500 maximum)

**Comment by Provolonage** [comment]
thx

**Comment by wakystuf** [comment]
Thanks! I think the trait parts are separate, fwiw, so I wouldn't mess with those for now.

Yeah, those Gnashast are real bad, particularly the collection bonuses. 

5-10 MP per turn from MP shouldn't actually be that bad in ESG with huge amounts of defensive MP capacity + Sim Camps, but the collection bonuses are pretty bad.

The Illo seem like the other way around with their main weakness being the poor base pop

**Comment by Provolonage** [comment]
the issue is since there are so many food multipliers in the game something like 5 food can easily become 5 mp a turn and now with food convo making mp is trivial as every eco behemoth basically makes 200+ mp a turn

**Comment by ThanosDeGraf** [comment]
I'd say we can double, or even quadruple the Tikanan per pop bonus. Otherwise as Provo said they just get overshadowed by one or two system improvements.

Idk what can be done for the Gnashast other than increasing the values. Their Col Bonus III I think is fine, since its DdtA is double that of Defend System. 

The second collection bonuses of them both are a bit lacking though.

I agree with waky on the Illo.

**Comment by Provolonage** [comment]
id rather just give ghast 1 indy base and another +1 on fertile. and give tik +2 food and another +2 on fertile, since the real issue is that mp gen is a very situational mechanic so making that better wont really fix the issue of not wanting these pops, illo should give +1 infl base and +2 on hot since thats what bhagba is on fertile

**Comment by ThanosDeGraf** [comment]
Haven't thought of giving them more baseline utility. That's a good idea.

**Comment by wakystuf** [comment]
I agree with Provo regarding the Illo.

Gnashast could be solved in a number of ways, but Provo's proposal seems fine. Still need to do something about the wretched collection bonuses.

5 (and an easy condition for 10) MP is still pretty reasonable. Like MP is a bit less useful than most FIDS, but with the ground battle changes + Sim Camps it's only a little bit worse (like, yes situational, but the "situation" is extremely common). And 5/10 is a pretty big number; basically nobody gets 5/10 food, science etc even with a harder-to-achieve condition (ex: on strat deposit, or anomaly, etc).

**Comment by NoProblemWithThisAcc** [comment]
I'd say the Illo can be kept in the curio pool (maybe with just a bit of a buff).
I agree with removing the Tikanan and Gnashast from the curio pool (after buffs for the pops in their own minor empires).
I'd like to suggest that the Yuusho should be removed from the curio pool instead of the Illo:

Per Pop Effect: +20 System capacity (30 on Sterile)
Trait I: "Hunting Culture" +20% Damage on Weapon Modules
Trait II: "Mud Stompers I" -10% Manpower Cost per troops on Ground Battles
Col Bonus II: +15% manpower capacity on System
Col Bonus III: +15% Manpower Replenishment on fleets outside borders

**Comment by wakystuf** [comment]
No, I think Cobbs' original idea is right: all minors should be in the curio pool. However, we should buff/rework the bad pops so that all of them are decent. Provo and Cobbs both had some ideas for how to implement that latter part, and I think there are a bunch of ways to do it as long as we do something.
